#%RAML 1.0 DataType
displayName: Beer
description: 
examples: 
  beer: !include examples/beer.json
  create-beer: !include examples/create-beer.json
properties:
  id:
    displayName: ID
    description: The URI of the resource. The ID is always returned but is not required to create a Beer
    type: string
    example: "https://mike.com/v1/beers/1"
    required: false
  identifier:
    displayName: Identifier
    description: The identifier of the beer
    type: string
    example: "1"
    required: true
  name:
    displayName: Name
    description: The name of the beer
    type: string
    example: Mike Beer
    required: false
  abv:
    displayName: Alcohol by Volume
    description: A % value of the alcohol content of the beer
    type: string
    required: false
    example: "5.5"
  breweries:
    type: array
    required: false
    items: !include brewery.raml
  
